### PR TITLE
Enhance & fix manifest

### PR DESCRIPTION
**Pull request by Eagle3386**
- Adds "applications" key (needed for coming sync-support of options, e. g. maps provider, display units)
- Adds "author" for proper credits
- Fixes keys ordering (all are alphabetical now)

### CODE REVIEW

**Comment by Eagle3386** [comment]
@gcp, I kept this PR clean, tight and only added stuff that makes extension reading/using easier.
Still, something must be wrong since you accept #18, but not this one.

What needs more polish on my end that you greenlight it?

**Comment by gcp** [comment]
I already explained that until there is something that actually requires sync there's no point in having an applications key. These are just pointless changes.

**Comment by gcp** [comment]
Just include the change to the manifest in the same pull that adds whatever requires sync support (but as already said, window position/size should not be synceed!).

**Comment by Eagle3386** [comment]
No need to be harsh. And that you thought I could've still missed the "don't even think about syncing window position/size" statement (after you stated it at least twice within this repository).
Oh boy, what an attitude.. 🤔

**Pull request closed without merging**
